//! Embedded adapter ELF blobs (generated by `zig build embed-adapters`).
pub const Blob = struct {
    name: []const u8,
    priority: u8,
    uses_vectors: bool,
    data: []const u8,
};

pub const blobs = [_]Blob{
    .{ .name = "compositor", .priority = 5, .uses_vectors = false, .data = @embedFile("blobs/compositor.elf") },
    .{ .name = "tactile-id", .priority = 3, .uses_vectors = false, .data = @embedFile("blobs/tactile-id.elf") },
    .{ .name = "neural-engine", .priority = 8, .uses_vectors = true, .data = @embedFile("blobs/neural-engine.elf") },
    .{ .name = "agent-runtime", .priority = 4, .uses_vectors = false, .data = @embedFile("blobs/agent-runtime.elf") },
};
